### ISSUE TITLE
postMessage should return how much ROSE it would require to submit the cross-chain message

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/sapphire-paratime#131]
https://github.com/oasisprotocol/sapphire-paratime/blob/55284f3951859c035dcc6e99aaf228d4acfaa880/contracts/contracts/opl/Endpoint.sol#L90

Without returning gas transferred to Celer MessageBus an Endpoint inheriting contract doesn't know how much it cost to send a message, so would be unable to charge a different user appropriately and rely on some external benevolent entity to ensure the contract has enough to pay for the relaying.

This could also cause havok if the contract is relaying messages to other chains and also trying to maintain an internal ROSE balance of external user deposits, the contracts internal accounting could have a mismatch of actual ROSE it holds vs how much it thinks it holds.

A temporary workaround would be to duplicate this code before calling `postMessage`, except `txSeq` is private so inaccessible to inheriting contracts:

```solidity
        bytes memory envelope = abi.encodePacked(
            bytes4(keccak256(_method)),
            txSeq,
            _message
        );
        uint256 fee = estimateFee(envelope.length);
```

**Comment by kostko** [comment]
I guess in this case it would be better if one could (also) estimate this in advance when needed? Because after a message is posted it may already be too late if you discover that the fee was too high.

So maybe having a nicer variant of the `estimateFee` method where the estimation would use a reasonably large value for `txSeq` (we only need it for deriving the approximate length, slight overestimation is probably ok).
