### ISSUE TITLE
Ensure support for Tenderly

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/sapphire-paratime#281]
##### SUMMARY

[Tenderly](https://tenderly.co/) is a popular dev environment that we should support.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Integrations/clients.

**Comment by CedarMist** [comment]
I spoke with Tenderly briefly in Barcelona.

We're unable to support Tenderly because it requires trace support, which you can't get from Testnet or Mainnet due to it being Confidential EVM.

iirc we're looking at trace support in the debug builds, but tenderly doesn't support (or seem to plan for support) uploading custom traces. So it seems tenderly is a no-go.

**Comment by aefhm** [comment]
I don't see a "won't do" label. I'm also okay if we close this for now.
