### ISSUE TITLE
Create a wrapper connector for web3-react@6

### ISSUE THREAD

**Issue by BerkliumBirb** [oasisprotocol/sapphire-paratime#55]
Right now you have to manually write wrapper to use web3-react connectors with web client library. It'll be great if you provide some canonical solution for that.

> *Also it'll be good to have wrapper for web3-react@8*

**Comment by nhynes** [comment]
I don't use react, but I'm happy to provide an integration. Would you mind posting your manual wrapper as a PR in the `clients/web3-react`  folder? I can help get it ready for merging in. Thanks!

**Comment by BerkliumBirb** [comment]
The problem with our current solution is that it only allows using sapphire. So I was wondering if you have any ideas of how to implement a wrapper connector that only wraps provider if it's connected to sapphire supported chains. And that can automatically unwrap if chain is changed by user (e.g. user changes it in MetaMask).

**Comment by nhynes** [comment]
You could check and then listen to the chain ID, then monkey patch when required. When the chain ID is `0x5aff` or `0x5afe` (saff or safe), then wrap (storing the original provider), otherwise set the object back to the original one.

The specifics of how to monkey patch depend on how clients access the object. For example, to patch metamask directly, you'd need to replace its `send` method, as clients may already have captured a reference to the original `window.ethereum` (so you can't replace it directly). If it's in some react store, and accesses to it are reactive, you can replace the object since there's one layer of indirection.

If you post some almost-working code, we can discuss and get it to a fully working state.

**Comment by ismae147** [comment]
Hi, i got this error using in react with typescript
<img width="795" alt="image" src="https://user-images.githubusercontent.com/9323138/193727282-7effd0e8-0ee0-45d7-940a-4677ae85df0d.png">

can you help me?

**Comment by nhynes** [comment]
Here's an example of doing that https://github.com/oasislabs/wordleish/blob/main/frontend/src/stores/ethereum.ts. I think that using a store (or equivalent) is the canonical solution, so I'm going to close this issue. If using a store ends up not working, I'm more than happy to reopen it.
